version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-parse:
    container_name: whirlpool-parse
    entrypoint: bash ./scripts/wait-for-it.sh
    build:
      context: ./
      dockerfile: Dockerfile
      target: whirlpool-parse-dev
    restart: on-failure
