version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-parse:
    container_name: whirlpool-parse
    entrypoint: bash ./scripts/wait-for-it.sh
    build:
      context: ./
      dockerfile: Dockerfile
      target: whirlpool-parse
    restart: on-failure
    depends_on:
      - whirlpool-rmq

  whirlpool-rmq:
    container_name: whirlpool-rmq
    hostname: whirlpool-rmq
    restart: on-failure
    image: rihbyne/whirlpool-rmq:latest
    ports:
      - "5672:5672"
      - "8080:15672"
